### PR TITLE
stable20160823

### PR DESCRIPTION
**Pull request by jbickar**
This is ready for testing. Let's figure out how to split it up.

### CODE REVIEW

**Comment by sherakama** [comment]
I will build

**Comment by sherakama** [comment]
Starting to build dev builds of each.

**Comment by sherakama** [comment]
grunt build:make:install --build-git-branch="stable20160823"

**Comment by sherakama** [comment]
JSV, JSPlus, and JSA all build with this branch using the "sites" option.

**Comment by sherakama** [comment]
@jbickar,

Will this need to be updated after the testing has been complete this week or is it still good for review?

**Comment by jbickar** [comment]
yeah, we'll want to update it.

**Comment by sherakama** [comment]
Ok, re-assign when ready or when it should be picked back up.

**Pull request closed without merging**
