### PR TITLE
Views security update for Anchorage sites

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- [DRUPAL-SA-CONTRIB-2017-068](https://www.drupal.org/node/2902604)

# Needed By (Date)
- Today, because I want to build the images today

# Criticality
- How critical is this PR on a 1-10 scale?  8, affects all sites on Anchorage

# Steps to Test

1. Check that they'll build; it's already been tested on Anchorage.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/DEVOPS-119

### CODE REVIEW

**Comment by sherakama** [comment]
No Travis on 4.x? Guess not. I'll build a couple and see.

**Comment by sherakama** [comment]
JSA and JSV built without issue. Going to assume the rest are good.

**Comment by jbickar** [comment]
You know what happens when you assume.

**Comment by sherakama** [comment]
Boom

**Comment by jbickar** [comment]
Carbecue.

**Pull request merged**
