### PR TITLE
HSDO-446: Make files for Jumpstart Lab based on JSA

### PR DESCRIPTION
**Pull request by kbrownell**
Hello Shea.  Let me know if there is any additional work to be done for this jumpstart-lab deployer directory.  The only module I added to the jumpstart-academic set of files I started with was the context_http_header module.

### CODE REVIEW

**Comment by sherakama** [comment]
This looks good. We will fix anything that comes up tomorrow.

**Comment by jbickar** [comment]
👏

Did we undo setting "contrib" as the default value for `subdir` in our makefiles, because hilarity?

**Comment by sherakama** [comment]
I don't think we set that value for the 5.x version. I think it only effected the 4.x stuff.

**Comment by jbickar** [comment]
Good. It saved some bits, but it was a case study in "unintended consequences".

**Comment by sherakama** [comment]
Yeah, and I'm pretty sure we have been bitten twice by it already.

Let's not make it a third.

**Pull request merged**
