### PR TITLE
Soe 834

### PR DESCRIPTION
**Pull request by cjwest**
Hey Greg,

This is not really a PR. It's a branch of the deployer that will bring in all the changes for the changes in the news feature.  There are 4 repos plus this that are ready for your review.

This line on down should be deleted once all the other PRs have been merged:
https://github.com/SU-SWS/stanford-jumpstart-deployer/blob/SOE-834/make/development/jumpstart-engineering.make#L87

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik & @cjwest,

Please also update any changes going in to the 4.x branch with the 5.x branch. I have been maintaining them separately for the last little while and I hope to move from 4.x shortly so we don't have to do this much longer.

**Comment by boznik** [comment]
woot!

**Comment by cjwest** [comment]
W00t! I'm looking forward to 5.x!

Jamie,

When is the sprint for the next release of JSE?

**Comment by tsui1** [comment]
It probably won't be until after 6/15 -- we might be able to fit in 1 sprint on it before things start ramping up again on the school site. We'll have to see what Tonja's/Mike's plans are and plan around that.

**Comment by boznik** [comment]
This has become out of date and inaccurate.

**Comment by boznik** [comment]
closing this pr as associated branches have been merged and this no longer reflects the current state.

**Pull request closed without merging**
