### PR TITLE
HSDO-938 Updated modules and incremented profiles for jsa & jsl

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Updated a few modules in JSA & JSL.
- Incremented JSA & JSL profiles to indicate release.

# Needed By (Date)
- End of Sprint 8/31

# Urgency
- Low

# Steps to Test

1. Build a production jsa & jsl site.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by boznik — APPROVED** [review]
Built jsa and jsl. working as expected.

**Comment by boznik** [comment]
updating branch

**Comment by pookmish** [comment]
Can we merge?

**Comment by boznik** [comment]
testing again post merge

**Pull request merged**
