### PR TITLE
Changed sources for simplepie and jquery cycle libraries.

### PR DESCRIPTION
**Pull request by sherakama**
…for library version.

# READY FOR REVIEW

# Summary
- Valid 3rd party sources for simplepie and jquery cycle

# Needed By (Date)
- ASAP

# Urgency
- High

# Steps to Test

1. Go Travis Go
2. Merge

# Affected Projects or Products
- All of them.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by jbickar — APPROVED** [review]

**Comment by sherakama** [comment]
Do I haz to fix the tests as well?

**Comment by jbickar** [comment]
Travis has been broken for a week or so. I haz a sad.

**Comment by sherakama** [comment]
@jbickar @kbrownell 

We haz green lights! Rdy for squashmerge.

**Comment by jbickar** [comment]
W00t! What did you fix in Travis?

**Comment by sherakama** [comment]
The new version of the drupal-extension was causing the errors. I just bound it to the one that works for us.
https://github.com/SU-SWS/stanford_travisci_scripts/commit/907d3b7a691f85fc78e33b43a8b4b83de01017d5

**Comment by kbrownell** [comment]
Oh man, thank you so much for tracing it down to that!

**Pull request merged**
