### PR TITLE
BASIC-1391: Prevent node save when deleting field collections. 

### PR DESCRIPTION
**Pull request by sherakama**
What was happening was that anytime a field collection was being deleted from a node it saved the parent node causing all of the node_save hooks to fire. This chain of events lead to pathauto picking up and incorrectly updating or creating a new alias.
- Avoids creating pathauto aliases and other hilarity.
- https://stanfordits.atlassian.net/browse/BASIC-1391
- https://www.drupal.org/node/2385985

To test:
1. Merge
2. Build a dev if https://github.com/SU-SWS/Stanford-Drupal-Profile/pull/58 has been merged or build a production JSA
3. Install JSA and ensure it goes all the way through
4. Create a new node that has a field collection on it
5. Delete that node
6. Check to see that path alias no longer exists.

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik FYI.

**Comment by jbickar** [comment]
Changes in `field_collection` between `7.x-1.0-beta8` and `7.x-1.0-beta11`:
- Added `hook_field_collection_item_label()` and support for entityreference
- Move FieldCollectionItemEntity to a separate include file
- Token support
- Fix for boolean fields
- Fix for revisions
- Skip saving host when host is being deleted.
-  Implemented `hook_admin_menu_map()`
- Fix for Cron WSOD caused by attempt of delete on non-object
- Fixes for updating host entities
- Form fixes
- Migration fixes
- PHP < 5.3 fix

**Comment by sherakama** [comment]
`Move FieldCollectionItemEntity to a separate include file` causes WSOD until cache clear... :( :-1:

**Comment by sherakama** [comment]
VPSA has been running beta10 for a few months now.

**Comment by jbickar** [comment]
WSODs keep me gainfully employed :+1:

**Comment by jbickar** [comment]
Error on JSA install:

```
JSA - Finished importing vocabularies.                                                                                                                                                                                     [ok]

Fatal error: Call to a member function hostEntity() on boolean in /Users/jbickar/Sites/64/sites/all/modules/contrib/field_collection/field_collection.module on line 539
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                         [error]
Error: Call to a member function hostEntity() on boolean in /Users/jbickar/Sites/64/sites/all/modules/contrib/field_collection/field_collection.module, line 539
```

**Comment by jbickar** [comment]
I can reproduce this error.

**Comment by sherakama** [comment]
@jbickar, 

`this error.` as in the install borks or the alias issue?

**Comment by jbickar** [comment]
Install borks with the `Fatal error: Call to a member function hostEntity() on boolean` error

**Comment by sherakama** [comment]
@jbickar I updated the patch and the thread for this: https://www.drupal.org/node/2385985

**Comment by boznik** [comment]
working!

**Pull request merged**
