### PR TITLE
Update JSE Prod to 5.x

### PR DESCRIPTION
**Pull request by cjwest**
@boznik,
I added the help module and alphabetized this section of the make file

### CODE REVIEW

**Comment by cjwest** [comment]
@boznik,
Ready for your review!

**Comment by boznik** [comment]
i'm getting errors with both running as command line make with deployer and with gepetto using this branch.

stanford_metatag_nobots is still listed as a dependency in stanford_sites_jumpstart_engineering, but is no longer available via the deployer.

that might be it though, i updated my local removing that depency and drush si ran without errors.

**Comment by cjwest** [comment]
@boznik : 
I removed the references to  stanford_metatag_nobots and tested it. It should be ready to go. 
However, it is dependent upon:
https://github.com/SU-SOE/stanford_sites_jumpstart_engineering/pull/41

**Comment by boznik** [comment]
@cjwest the production version of stanford_sites_jumpstart_engineering needs to have stanford_metatag_nobots replaced with nobots.

**Comment by cjwest** [comment]
@boznik, Thanks for finding that illusive tag! It should be working now.

**Pull request merged**
