### PR TITLE
Soe 492

### PR DESCRIPTION
**Pull request by cjwest**
@boznik : Please review

### CODE REVIEW

**Comment by boznik** [comment]
line 30 needs to be:
projects[stanford_drupal_profile][download][url] = "git@github.com:SU-SWS/Stanford-Drupal-Profile.git"

**Comment by boznik** [comment]
the footer logo is missing on prod

**Comment by boznik** [comment]
--- Failed scenarios:

```
features/jse_get_help.feature:7
features/site_owner.feature:59
features/stanford_jse_homepage/homepage_hoover.feature:20
features/stanford_jse_homepage/homepage_hoover.feature:21
features/stanford_jse_homepage/homepage_hoover.feature:33
features/stanford_jse_homepage/homepage_hoover.feature:34
features/stanford_jse_homepage/homepage_hoover.feature:45
features/stanford_jse_homepage/homepage_hoover.feature:46
```

209 scenarios (201 passed, 8 failed)
907 steps (899 passed, 8 failed)
30m15.55s (17.83Mb)

**Comment by boznik** [comment]
@cjwest ,

plz test with my change

**Comment by cjwest** [comment]
testing....

**Comment by cjwest** [comment]
@boznik  - Thanks for these failed scenarios. See my comments

features/jse_get_help.feature:7 - I think this one is the qualtrics form not getting loaded or the site owner not getting logged in

These following test are tests where the site owner needs to log in to make things happen. For some reason, logging in seems to fail occasionally and the dependent tasks fail as well

features/site_owner.feature:59
features/stanford_jse_homepage/homepage_hoover.feature:20
features/stanford_jse_homepage/homepage_hoover.feature:21
features/stanford_jse_homepage/homepage_hoover.feature:33
features/stanford_jse_homepage/homepage_hoover.feature:34
features/stanford_jse_homepage/homepage_hoover.feature:45
features/stanford_jse_homepage/homepage_hoover.feature:46

**Comment by cjwest** [comment]
@boznik  - It appears that we have one remaining critical issue. We need to update the WYSIWYG to display the logo. I'll look at it on Monday.

https://stanfordits.atlassian.net/browse/SOE-586

**Comment by cjwest** [comment]
@boznik , Are you testing on the jse-dev branch of Linky-click?

**Comment by boznik** [comment]
@cjwest ,
yes, working on the jse-dev branch of linky clicky

**Comment by tsui1** [comment]
Waiting for:

https://github.com/SU-SWS/stanford_jumpstart/pull/57
https://github.com/SU-SWS/stanford_sites_jumpstart/pull/22

**Comment by cjwest** [comment]
@boznik : Please review.

**Comment by boznik** [comment]
@cjwest ,
stanford_jumpstart has the tag 7.x-4.5+30-dev in jumpstart.make production build, but this tag doesn't have the latest changes that fix the pathologic issues.

**Comment by cjwest** [comment]
Yeah. I just discovered it was listed twice in the makefile.

I'm testing it again.

CJ

**Comment by boznik** [comment]
looks like stanford sites jumpstart is correct.

**Comment by cjwest** [comment]
@boznik , please test again. 
By the way, we have not conquered 
https://stanfordits.atlassian.net/browse/SOE-541

**Comment by sherakama** [comment]
Im getting an error:

`No release history was found for the requested project (stanford_drupal_profile).                                                                                                                                                                                                                                                                                [error]`

https://github.com/SU-SWS/stanford-jumpstart-deployer/blob/SOE-492/make/production/jumpstart-engineering.make#L102

**Comment by boznik** [comment]
me too, this is a recent error.

**Comment by sherakama** [comment]
Removing the line linked above allows the build to happen without error. I couldn't find a reference to what that was for.

**Comment by boznik** [comment]
the error was introduced in this commit:

5bd7b23b829efe3e9

looks like the project info was deleted

**Comment by sherakama** [comment]
Ah, good ol' fashioned pull'n stuff out of thin air. 

@cjwest, I believe the line you are looking for is:
`projects[stanford][download][tag] = '7.x-2.2+13-dev'`

**Comment by sherakama** [comment]
Other than the comment above and the outstanding issue with the qualtrix link this build looks good.

**Comment by boznik** [comment]
placing the project info back into the make file fixed the error for me:
projects[stanford_drupal_profile][type] = "module"
projects[stanford_drupal_profile][download][type] = "git"
projects[stanford_drupal_profile][download][url] = "git@github.com:SU-SWS/Stanford-Drupal-Profile.git"
projects[stanford_drupal_profile][download][tag] = "7.x-2.2+13-dev"

**Comment by jbickar** [comment]
`...[type] = "profile"`

And probably:

`projects[stanford]...`

**Comment by sherakama** [comment]
@cjwest @boznik @jbickar,

There is already one reference to the installation profile being pulled in:
https://github.com/SU-SWS/Stanford-Drupal-Profile/blob/7.x-2.x/make/stanford.make#L350

No need to define it again. Simply change the tag version on the `projects[stanford]` definition as mentioned in the comment 4 above. 

This is a prime example of why I want to flatten these files. It is very difficult to find out where everything is and what is the final defining value.

**Comment by cjwest** [comment]
Thanks @jbickar, @sherakama, and @boznik, for looking at this. I got a bit fuzzy brained last night.

**Comment by cjwest** [comment]
Hah! I forgot to push my latest changes.

**Comment by sherakama** [comment]
Are you going to push them up?

**Comment by cjwest** [comment]
@boznik, Please review

**Comment by boznik** [comment]
this looks pretty good, but i have just replicated this issue on this latest build:
https://stanfordits.atlassian.net/browse/SOE-541
behat results:
--- Failed scenarios:

```
features/jse_get_help.feature:7
features/site_owner.feature:59
features/stanford_jse_homepage/homepage_hoover.feature:20
features/stanford_jse_homepage/homepage_hoover.feature:21
features/stanford_jse_homepage/homepage_hoover.feature:33
features/stanford_jse_homepage/homepage_hoover.feature:34
features/stanford_jse_homepage/homepage_hoover.feature:45
features/stanford_jse_homepage/homepage_hoover.feature:46
```

209 scenarios (201 passed, 8 failed)
907 steps (899 passed, 8 failed)

**Comment by boznik** [comment]
good news:
https://stanfordits.atlassian.net/browse/SOE-541
this was caused by a destructive behat test. the install profile does fix this issue.

**Comment by cjwest** [comment]
Bad Behat!

**Comment by cjwest** [comment]
I think the problem may lie with the Behat tests and not the deploy. Have you looked at the tests and walked through them to verify that they are actual problems?

**Comment by boznik** [comment]
walked through failed tests and confirmed issues are with tests.

**Comment by cjwest** [comment]
Yes!!! Thank you @boznik and @sherakama !

**Comment by tsui1** [comment]
:clap: :tada:

**Pull request merged**
