### PR TITLE
Revert major version jumps in JSE

### PR DESCRIPTION
**Pull request by jbickar**
FYI @cjwest @boznik

### CODE REVIEW

**Comment by cjwest** [comment]
Thank you, @jbickar, for pointing this out. Yeah. I was unclear about how to proceed with contrib modules. I would really like that thought process explained in the documentation.  Will you please add your $0.02:
https://asconfluence.stanford.edu/confluence/pages/replycomment.action?commentId=1107099723&pageId=978485714

**Comment by jbickar** [comment]
Added a comment on the Confluence page.

**Comment by sherakama** [comment]
So this is to avoid unnecessary major version jumps until sites core can get its up to the latest?

**Comment by jbickar** [comment]
Yeah, and unnecessary one-offs for modules that aren't used in the product.

**Comment by jbickar** [comment]
And if we're doing major version jumps, I want it to be intentional, and ensure we have test coverage.

**Comment by sherakama** [comment]
I like all those reasons. Thanks.

**Pull request merged**
