### PR TITLE
Add stanford_field_formatters, dependency for stanford_bean_types

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- Add a new dependency for `stanford_bean_types`

# Needed By (Date)
- Immediately for development builds
- Not sure if production builds are pointing at a release of `stanford_bean_types` that includes this dependency yet

# Criticality
- How critical is this PR on a 1-10 scale? 10
- It affects every site and product

# Steps to Test

1. Build the products
2. Let Travis do its thing

# Affected Projects or Products
- Arrything

# Associated Issues and/or People
- https://github.com/SU-SWS/stanford_bean_types/pull/57
- Anyone who should be notified? ( @pookmish )

### CODE REVIEW

**Comment by sherakama** [comment]
Woot Travis. You're all green.

Ok, I can wait for the production build pr.

**Review by sherakama — APPROVED** [review]
Thank you Travis.

**Comment by sherakama** [comment]
Oh, and thank you John.

**Comment by jbickar** [comment]
Don't thank me, thank Travis.

**Comment by jbickar** [comment]
`stanford_field_formatters-7.x-1.1` is now in all of the production builds for products. I just wasn't sure whether the version of `stanford_bean_types` in all of the production builds is yet up to a version that requires `stanford_field_formatters`, but it can't hurt to have it in there.

**Pull request merged**
