### PR TITLE
Patch webform for php 7.1

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
Another PHP 7 fix.
RE: https://www.drupal.org/node/2811063

# Needed By (Date)
- Sometime, anytime, before release 4.15

# Urgency
- Not urgent.

# Steps to Test

* Build a JSL website without the patch
* Switch PHP to 7.1
* Navigate to any page and see PHP error
* Apply patch and see error go away.

# Affected Projects or Products
- Errything.

# Associated Issues and/or People
- RE: https://www.drupal.org/node/2811063

### CODE REVIEW

**Comment by jbickar** [comment]
@sherakama I haven't forgotten about this, just haven't gotten 
round-tuit

**Comment by sherakama** [comment]
Haha, you found a round tuit!

**Comment by jbickar** [comment]
@sherakama FYI, I had to clean up merge conflicts anyhow, so I took the opportunity to do some organization in the `patches.make` files. This PR is now a little bit bigger as a result; probably could use a second set of eyes that all the necessary patches are in there.

The patch for `date` is only needed for `7.x-2.9` and lower:

```
./development/product/drupalcamp/contrib.make:projects[date][version] = "2.9"
./development/product/jumpstart/contrib.make:projects[date][version] = "2.10-rc1"
./development/product/jumpstart-academic/contrib.make:projects[date][version] = "2.10-rc1"
./development/product/jumpstart-engineering/contrib.make:projects[date][version] = "2.9"
./development/product/jumpstart-lab/contrib.make:projects[date][version] = "2.10-rc1"
./development/product/jumpstart-plus/contrib.make:projects[date][version] = "2.10-rc1"
./development/product/jumpstart-vpsa/contrib.make:projects[date][version] = "2.9"
./production/product/jumpstart/contrib.make:projects[date][version] = "2.10-rc1"
./production/product/jumpstart-academic/contrib.make:projects[date][version] = "2.10-rc1"
./production/product/jumpstart-engineering/contrib.make:projects[date][version] = "2.9"
./production/product/jumpstart-lab/contrib.make:projects[date][version] = "2.10-rc1"
./production/product/jumpstart-plus/contrib.make:projects[date][version] = "2.10-rc1"
```

That should explain why only some of the `patches.make` files have the `date` patch from https://www.drupal.org/node/2375235

**Comment by jbickar** [comment]
I love you, Travis.

**Comment by jbickar** [comment]
@sherakama this is GTG by me. Please review the reorganization of the `patches.make` files to ensure that nothing got missed.

**Pull request merged**
