### PR TITLE
SOE-1579: update news and jumpstart_engineering

### PR DESCRIPTION
**Pull request by cjwest**
# READY
- Built and tested with latest Behat tests.

# Summary
- Updates the deployer to use the deprecated credits in favor of news caption/credits

# Needed By (Date)
- N/A

# Urgency
-  Needed before we roll the next PICAL site

# Steps to Test

1. Build a jse production site
2. Verify that the image credits field does not display when editing  a news item

# Affected Projects or Products
- None. Changes in this PR should be for JSE production sites only.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOE-1684
- https://github.com/SU-SWS/stanford_news/releases/tag/7.x-3.6%2B23-dev
- https://github.com/SU-SOE/stanford_jumpstart_engineering/releases/tag/7.x-5.4%2B12-dev
- @boznik 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by boznik** [comment]
@cjwest 
let's get a tag of stanford_events_importer that includes this commit:
92d40b6f7c9451a8156cfc2944322d8b0cad9a02

**Comment by cjwest** [comment]
@boznik,
I tagged the events_importer and updated the deployer. It still needs testing.

**Comment by cjwest** [comment]
i hate that "close and comment" button!

**Comment by boznik** [comment]
i think john requested a full release on this

**Comment by cjwest** [comment]
Okay, we have a full release on this little boy.

**Review by boznik — COMMENTED** [review]
All tests passed

**Pull request merged**
