### PR TITLE
Added Video Embed Field - dependency of stanford_events_recap

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- added video_embed_field for products that use stanford_events_recap (submodule of stanford_events_importer)
- stanford_events_recap is not enabled by default on any product at this time.
- Tested stanford_events_recap with youtube video [here](https://travis-ci.org/SU-SWS/stanford_events_importer/builds/229196498#L991)

# Needed By (Date)
- when you can

# Urgency
- not high urgency

# Steps to Test

1. run products tests as seen in travis.

### CODE REVIEW

**Comment by kbrownell** [comment]
Hello Mike.  Before reviewing, can you fill out our PR template: https://sites.stanford.edu/sws-developers/creating-and-reviewing-pull-request?  That may help answer my review question, which is why only jumpstart-academic, jumpstart-plus, and jumpstart?  stanford_events_importer-7.x-3.x appears in a number of other product-specific development make files, which will presumably require this video_embed_field module as well.

**Comment by pookmish** [comment]
@kbrownell, I added the module for the 3 products that were missing it. jslabs already had the module added. so with this PR, 4 of the 5 products will have the module. SOE would be the only remaining. They handle that correct?

**Comment by jbickar** [comment]
Per our discussion:

- This is a dependency for `stanford_events_recap`, not `stanford_events_importer`
- `stanford_events_recap` is not enabled by default by any of our products currently.

@sherakama, do we add dependencies to the .make files in `stanford-jumpstart-deployer` when they are not installed by default in products? I can't remember if we have this documented.

**Comment by sherakama** [comment]
The product should always contain everything it needs to function. It should not have to install anything in order to turn something on. Include the dependencies of all modules in the make file.

**Comment by jbickar** [comment]
Think about that for a sec.

**Comment by sherakama** [comment]
Monkeys

**Comment by jbickar** [comment]
I wasn't even supposed to be here today

**Comment by jbickar** [comment]
Per discussion, @sherakama sez:
```
Best practice says to include the dependencies
with composer, npm, bower, etc they do it for you
With drush.make files we get "close enough"
```

Decision: We'll do it going forward but not retroactively

**Comment by jbickar** [comment]
Back to @pookmish. Please do the following:

1. Update the PR description to indicate that this is a dependency for `stanford_events_recap`, not `stanford_events_importer`. (We do refer back to PRs to determine what "Past Us" was thinking)
2. Note in the description that `stanford_events_recap` is not enabled by default in any of the products, but that (per discussion), its dependencies should be included in `.make` files
3. Update all `contrib.make` files (both production and development) to include `video_embed_field`. Specify version number.
4. Provide steps to test the functionality of `video_embed_field` (or a link to a Behat test).

**Comment by pookmish** [comment]
Added additional descriptions. I didnt add it video_embed_field to SOE though. should i do that?

**Comment by jbickar** [comment]
Go Travis, it's your birthday.

**Review by jbickar — APPROVED** [review]

**Pull request merged**
