### PR TITLE
HSDO-293: Courses 4.x upgrade for jsa js+ jspvpsa jse

### PR DESCRIPTION
**Pull request by sherakama**
# Stanford Courses Upgrade
### To test:
1. Build a new site of each product JS+, JSA, JSVPSA, JSE
2. Enable stanford_courses
3. Create an importer and import some courses
4. Test to ensure values in field collections are correct
5. Profit

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik, Can you test JS+ and JSA
@cjwest , Can you test JSE

Thanks!

**Comment by cjwest** [comment]
Hey @sherakama ,
In order for me to test with JSE, it needs to be merged with:
https://github.com/SU-SWS/stanford-jumpstart-deployer/pull/79

How would you like for me to proceed?

Caryl

**Comment by sherakama** [comment]
Why do you need to test with #79? 

In any case, you can create a temporary branch on your local and merge these two branches together if you need to.

**Comment by cjwest** [comment]
> The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as
> <em>sites/all/modules</em>. Missing modules: <span class="admin-missing">Nobots</span>' in /Users/cjwest/Documents/htdocs/jse.dev/includes/install.core.inc:773

Okay, @sherakama, I'll do that.

**Comment by cjwest** [comment]
Interesting, I received this when enabling modules:

> The stanford_easy_wysiwyg_css module is missing, so the following module will be disabled: stanford_jumpstart_wysiwyg.

**Comment by cjwest** [comment]
@sherakama,
I'm seeing a problem with the field collections for sections. It seems like it is repeating the same data for each section, but I'm not sure where the data is coming from. I used this as my import URL:

https://explorecourses.stanford.edu/search;jsessionid=1s6ml2cbu9qtacz6xzs2jm7kz?view=catalog&academicYear=&page=0&q=AFRICAST&filter-departmentcode-AFRICAST=on&filter-coursestatus-Active=on&filter-term-Summer=o

**Comment by sherakama** [comment]
@cjwest, which course is this for?

**Comment by cjwest** [comment]
AFRICAST 299: Independent Study or Directed Reading
Terms: Aut, Win, Spr, Sum | Units: 1-10 | Repeatable for credit | Grading: Letter or Credit/No Credit
Instructors: Hubbard, L. (PI) ; Roberts, R. (PI) ; Samoff, J. (PI)
Schedule for AFRICAST 299

**Comment by cjwest** [comment]
The link in my earlier comment is breaking early. Try this [link](https://explorecourses.stanford.edu/search?view=catalog&filter-coursestatus-Active=on&page=0&catalog=&academicYear=&q=AFRICAST+independent+study&collapse=#)

**Comment by sherakama** [comment]
Thanks for that feedback @cjwest. I confirmed that the instructors were being duplicated. 
Something funny is going on with that field so I have removed it from the mapping for the time being. I will add back in again and mark for review.

**Comment by sherakama** [comment]
@cjwest,

I have put in a PR that should better handle the multiple field value fields in field collections: https://github.com/SU-SWS/stanford_feeds_helper/pull/3

Please test again using that branch of the stanford_feeds_helper module.

**Comment by cjwest** [comment]
@sherakama, will you please merge with 5.x branch? That would be super helpful for me!

I'm getting this error:

> exception 'Exception' with message 'Required modules: Required modules not found.                                                         [error]

The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as
<em>sites/all/modules</em>. Missing modules: <span class="admin-missing">Nobots</span>' in
/Users/cjwest/Documents/htdocs/jse.dev/includes/install.core.inc:773

**Comment by sherakama** [comment]
Merge what with 5.x?
This branch? 

Or at least include nobots

**Comment by sherakama** [comment]
Ok,  I have merged 5.x in to this.

**Comment by cjwest** [comment]
Hey @sherakama,
I'm still seeing the same data repeating

Caryl

**Comment by sherakama** [comment]
Did you test with the refactor branch of the feeds helper module and the latest 4.x of stanford courses?

**Comment by cjwest** [comment]
I don't know. 

> stanford-jumpstart-deployer$ git status
>  On branch HSDO-293
> nothing to commit, working directory clean

I deleted the directory this morning and pulled the latest

**Comment by cjwest** [comment]
Okay, I assumed that this was already pulled in by the deployer:
 SU-SWS/stanford_feeds_helper#3

Will pull it and try again

**Comment by sherakama** [comment]
@cjwest,

I have pushed another fix to the refactor branch of the feeds_helper module. Could you please review again.

Thanks for all the testing!

**Comment by boznik** [comment]
@sherakama the instructor isn't populating for me.

**Comment by cjwest** [comment]
Hi Shea,

Weird. The field collections are getting some valid data, however, it is repeating strangly. 
For example, for AFRICAST 199, I see:

## Section | Repeats | co-instructor(s)

1            |    3          | none
2            |    3          | Hubbard, Samoff
3            |    3          | Hubbard, Roberts
4            |    3          | Samoff, Assenyoh
5            |    1          | Stanton

**Comment by cjwest** [comment]
Oh. Wait! There are multiple sections for each term!
It's looking correct!

**Comment by cjwest** [comment]
@sherakama,

It looks like it is populating properly for me!

W00t!

**Comment by boznik** [comment]
@sherakama it looks like instructor is populating the advanced section. This is working as expected.

**Pull request merged**
