### PR TITLE
Update Stanford-Drupal-Profile to 7.x-2.3

### PR DESCRIPTION
**Pull request by jbickar**
I'm telegraphing my moves, but I think you can see where I'm headed. I don't think this one needs a tag, just a merge.

### CODE REVIEW

**Comment by sherakama** [comment]
The code looks correct but have you tested building each of the products?

If not I can.

**Comment by jbickar** [comment]
I'll take JSA and JS+

**Comment by jbickar** [comment]
Protip: You get a lot fewer errors when you pass the correct path to the make file to `drush make`.

**Comment by sherakama** [comment]
And when you remove the previous site before building...

**Comment by jbickar** [comment]
Clownshoes.

**Comment by jbickar** [comment]
JS+, JSA, JSE all check out.

**Comment by sherakama** [comment]
JSV JSVPSA are good

**Comment by tsui1** [comment]
:+1:

**Pull request merged**
