### PR TITLE
Upgrade VBO to 3.4 release

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Update fixes the VBO issue for the manage/content debacle we had last week.
- 

# Needed By (Date)
- Sometime between now and the next sites release.

# Urgency
- Moderate

# Steps to Test

1. Build a JSA with this branch
2. Navigate to admin/mange
3. Select a number of items from the list of content
4. Select delete option from VBO options
5. Submit and confirm delete
6. Run cron
7. See correct nodes were deleted

# Affected Projects or Products
- All products and sites.

# Associated Issues and/or People
- https://www.drupal.org/project/views_bulk_operations/releases/7.x-3.4

### CODE REVIEW

**Comment by jbickar** [comment]
More critical is getting a new release of `stanford_manage_content` stamped and put into `stanford-jumpstart-deployer`. We can use this branch for that.

**Comment by sherakama** [comment]
Either PR will fix the issue. This update will fix the manage content bug even if we don't change the VBO field.

**Comment by sherakama** [comment]
Try this branch out with the bad view.

**Comment by jbickar** [comment]
Gotcha.

**Comment by jbickar** [comment]
Well ain't that some stuff.

**Comment by jbickar** [comment]
Diff from 3.3 to 3.4: https://gist.github.com/jbickar/1849c3debfcfd04034a5bfd5e6b06598

**Comment by sherakama** [comment]
It was all this junk that was removed that was causing the issue:
https://gist.github.com/jbickar/1849c3debfcfd04034a5bfd5e6b06598#file-vbo-diff-patch-L702

**Comment by jbickar** [comment]
JSA production build works and all Behat tests pass.

**Comment by jbickar** [comment]
- JSV development builds
- JSV production builds and installs; Behat tests all pass

**Comment by jbickar** [comment]
- JS+ development builds
- JS+ production builds and installs; Behat tests all pass

**Comment by kbrownell** [comment]
JSE development builds
JSE production builds and installs: Behat failures:
    features/all_sites.feature:42
    features/jse_courses_importer.feature:7
    features/jse_event_importer.feature:7
    features/jse_event_series.feature:31
    features/jse_full_html.feature:23
    features/jse_get_help.feature:7
    features/jse_metatag.feature:7
    features/stanford_affiliate_organization/jse_affiliate_organization_pages.feature:12

**Comment by jbickar** [comment]
- JSA development builds
- DrupalCamp development builds
- JS Lab development builds
- JS Lab production builds and installs (Behat todo)
- JSVPSA dev builds

**Comment by jbickar** [comment]
I think our new fancy expando-Search box is what's causing `features/all_sites.feature:42` to fail.

**Comment by jbickar** [comment]
JSL production only had two Behat test failures:
```
linky_clicky/includes/features/all_sites.feature:37
linky_clicky/includes/features/all_sites.feature:42
```
 PR sent for 37 and 42 is the issue I mentioned above. I'll have to look into that, but it's not related to this PR.

**Comment by jbickar** [comment]
OK we'll have to update the Behat test for expando-Search. I tested with keyboard nav and VoiceOver, both with and without Javascript, and the search form works fine. So I think it's a failure of the Feature, not the form.

I think this is GTG. One last check.

**Comment by sherakama** [comment]
Thanks for this work!

**Pull request merged**
