### PR TITLE
HS-88 Update stanford_manage_content

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Update stanford_manage_content to fix the VBO issue that could delete unwanted nodes.

# Needed By (Date)
- asap

# Urgency
- High

# Affected Projects or Products
- JSA sites and anchorage

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
@pookmish, this is for Anchorage sites?

**Comment by pookmish** [comment]
yup it is

**Comment by jbickar** [comment]
_FINE_

**Comment by jbickar** [comment]
This is from that conversation that we had in Slack and I said, "Send me a PR?"

**Comment by pookmish** [comment]
yup it is

**Comment by jbickar** [comment]
Well chop off my legs and call me Shorty.

**Review by jbickar — APPROVED** [review]
All the prod builds work.

**Pull request merged**
