### PR TITLE
5.2

### PR DESCRIPTION
**Pull request by cjwest**
@boznik,

I had tagged some repos and they got lost when we deleted this branch. I'm testing them now, but this explains the missing drupal_add_css().

### CODE REVIEW

**Comment by boznik** [comment]
the tagged repos themselves weren't lost. just them being pointed to on the test branch...right? The other repos pointed to on the deployer test branch were only deleted if they were merged.

**Comment by cjwest** [comment]
Right. The tagged repos are not lost, however, we need to get them into production.

**Comment by boznik** [comment]
running deploy suite:

--- Failed scenarios:

```
features/jse_event_series.feature:31
features/jse_get_help.feature:7
features/stanford_affiliate_organization/jse_affiliate_organization_pages.feature:12
```

100 scenarios (97 passed, 3 failed)
472 steps (466 passed, 3 failed, 3 skipped)

## 11m10.30s (15.52Mb)

features/jse_event_series.feature:31

## behat feedback: needs api

features/jse_get_help.feature:7

## behat feedback: Text source=soe not found with element a". (Exception)

features/stanford_affiliate_organization/jse_affiliate_organization_pages.feature:12
behat feedback: No region "Main Bottom" found on the page http://local.jse/. (Exception)

**Comment by boznik** [comment]
behat errors outside scope of this pr

**Pull request merged**
