### PR TITLE
Updated all products to use image_styles 4.x / 4.0

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW
# Summary

- Updates all products to use the 4.x / 4.0 release of the stanford_image_styles module
- New dependency on contrib

Behat tests have been updated for the 4.0 version so the coverage on this PR is really good.

# Needed By (Date)
- Next sites release (March 15?)

# Urgency
- Not urgent but would be good to get out sooner rather than later.

# Steps to Test

1. Let Travis build all of the products and run the automated tests
2. Rejoice. 

# Affected Projects or Products
- Everything.

# Associated Issues and/or People
- https://github.com/SU-SWS/stanford_travisci_scripts/pull/15
- Wait until that pull request has been merged before running the tests.

### CODE REVIEW

**Comment by jbickar** [comment]
Good. I was thinking I would run out of deployer PRs after merging that one last week.

WHEW!

**Comment by sherakama** [comment]
Depends on: https://github.com/SU-SWS/stanford_travisci_scripts/pull/15

**Comment by sherakama** [comment]
@jbickar PR has been merged.

**Comment by jbickar** [comment]
Once again, patience pays off.

**Comment by jbickar** [comment]
There's no `.travis.yml` file in this branch, so no Behat tests. I guess let's wait for #127 ?

**Pull request merged**
