### PR TITLE
PHP7 compatibility fix for feeds_tamper

### PR DESCRIPTION
**Pull request by sherakama**
Patch fixes a critical error in PHP7 but is also applicable to PHP5

https://www.drupal.org/node/2567431

### CODE REVIEW

**Comment by boznik** [comment]
Builds failing due to stanford_alt_check requirement.
will test manually adding it.

**Comment by sherakama** [comment]
alt_check should have been added to each drush.make file and profile. Did one or more get dropped?

**Comment by boznik** [comment]
i think they got added, but those changes weren't merged into this branch

**Comment by sherakama** [comment]
I just tried out GitHubs merge tool. It works very well.

**Comment by jbickar** [comment]
Development products all build. I had to push a change for `drafty` to jsplus.

**Comment by jbickar** [comment]
`jslab` production build fails with two errors:

```
 * [@self.0] stanford_sites_jumpstart_lab cloned from git@github.com:SU-SWS/stanford_sites_jumpstart_lab.git.                                                                                                              [ok]
 * [@self.0] Unable to check out tag 7.x-5.0.                                                                                                                                                                              [error]
 * [@self.1] stanford_jumpstart_lab cloned from git@github.com:SU-SWS/stanford_jumpstart_lab.git.                                                                                                                          [ok]
 * [@self.1] Unable to check out tag 7.x-5.0.                                                                                                                                                                              [error]
```

**Comment by jbickar** [comment]
Everything builds except for `production/jumpstart-lab`.

**Comment by sherakama** [comment]
Production jumpstart lab is still placeholder. That is acceptable.

**Comment by jbickar** [comment]
That was my guess. GTG on my end, then.

**Comment by sherakama** [comment]
Thank you.

**Pull request merged**
