### PR TITLE
Depts

### PR DESCRIPTION
**Pull request by cjwest**
This PR is for repositories associated with JSE Departments

### CODE REVIEW

**Comment by cjwest** [comment]
Hi @boznik,

Taking far too much time... anyway, it's ready! please check!

Thanks,
Caryl

**Comment by cjwest** [comment]
Okay @boznik,

Here's the latest for the deployer!!!

**Comment by boznik** [comment]
behat deploy results:

--- Failed scenarios:

    /Users/ggarvey/www/linky_clicky/includes/features/all_sites.feature:42
    features/jse_event_series.feature:31
    features/jse_get_help.feature:7
    features/stanford_affiliate_organization/jse_affiliate_organization_pages.feature:12

100 scenarios (96 passed, 4 failed)
472 steps (461 passed, 4 failed, 7 skipped)
17m59.10s (15.58Mb)

**Comment by cjwest** [comment]
Hey @boznik,

Will you please look at this again. I did more alphabetizing. Here are the current Behat results:

`
--- Failed scenarios:

    /Users/cjwest/Documents/htdocs/behat/linky_clicky/includes/features/all_sites.feature:42
    features/jse_event_series.feature:31
    features/jse_get_help.feature:7
    features/stanford_affiliate_organization/jse_affiliate_organization_pages.feature:12`

**Pull request merged**
