### PR TITLE
Remove dompdf library one-off

### PR DESCRIPTION
**Pull request by jbickar**

### CODE REVIEW

**Comment by sherakama** [comment]
@jbickar,

Can't remove the production one until a new tag is cut for Stanford Drupal Profile. It still references the old dompdf library.

**Comment by sherakama** [comment]
Should we cut a new +N-dev tag?

**Comment by jbickar** [comment]
Good catch. I think I'm going to make a pre-release off of `uat20151005` shortly. I'll return to this.

**Comment by jbickar** [comment]
Depends on https://github.com/SU-SWS/stanford-jumpstart-deployer/pull/81 now I think.

And need to remove it elsewhere, because https://github.com/SU-SWS/stanford-jumpstart-deployer/commit/e09d1ddfc8d560a225af5e25018b0638b1b0dafa

**Comment by sherakama** [comment]
#81 was merged. I think we are good to go on this.

**Comment by jbickar** [comment]
7.x-4.x is dormant.

**Comment by sherakama** [comment]
It IS winter time. The 4.x usually wakes up fresh in the spring.

**Pull request closed without merging**
