### PR TITLE
7/25/16 Sites updates

### PR DESCRIPTION
**Pull request by jbickar**

### CODE REVIEW

**Comment by sherakama** [comment]
Going to leave a trail of notes here to test as I am looking at the version diffs:
1. block_titlelink has added a permission to be able to set the title, removed php processing, added tokens, and moved from preprocess hook to a process hook.
2. colorbox min plugin version is now 1.6.1 from 1.3.21. The rel property on links have changed to data-xyz. Will need to look at our gallery feature to ensure this didn't break anything.
3. file_entity made a number of adjustments to the way the files are being rendered. Should check for anything that actually uses this module. Many other integrations and changes.
4. filefield_paths has new temp upload location setting. 
   Has database updates (drush updb)
   has lots of new processing on the paths including redirects and new hooks.
5. Flag has new access checks for flagging pages.
6. GA added colorbox tracking.
7. Link has new token support but nothing major.
8. Metatag - Changelog and diff are massive. Resorting to behat.
9. Mollom - Removed ping and content moderation services. 
10. Node clone - Bug fixes around token and clone action 
11. Views - Has a bunch of new field handlers.

**Comment by sherakama** [comment]
We don't appear to be using block_titlelink as a default in any of our projects. Not going to worry about permission changes.

**Comment by sherakama** [comment]
Colorbox is currently at 1.5.14. Will add to this PR for upgrade.

**Comment by jbickar** [comment]
Yeah, I'm staging `colorbox-1.6.4` for the next round of Sites updates. `colorbox` and `stanford_gallery` still work with `1.5.14`, but upgrayedd will happen soon.

**Comment by sherakama** [comment]
filefield_paths look good.

**Comment by sherakama** [comment]
Flag works

**Comment by sherakama** [comment]
Google analytics enables and colobox modal tracking is enabled by default.

**Comment by sherakama** [comment]
clone works.

**Comment by sherakama** [comment]
views check out and function.

**Comment by sherakama** [comment]
Mollom enables and is configurable. Did not test any transactions.

**Comment by sherakama** [comment]
👍 , code looks good. 

Shall I merge?

**Comment by jbickar** [comment]
Dooo eeet

**Pull request merged**
