### PR TITLE
Update version of Stanford-Drupal-Profile

### PR DESCRIPTION
**Pull request by jbickar**

### CODE REVIEW

**Comment by jbickar** [comment]
This will need https://github.com/SU-SWS/stanford_sites_jumpstart/pull/27 and https://github.com/SU-SWS/stanford_sites_jumpstart_academic/pull/17 to be merged and then new tags published and added to this PR.

**Comment by sherakama** [comment]
JSV Builds and works.

**Comment by sherakama** [comment]
JSPlus now works with block_class update.

**Comment by sherakama** [comment]
Ok, builds are working. I will have to test the 4.5.1 -> 4.6 upgrade path next.
A few parts have moved.

**Comment by sherakama** [comment]
I ran a test upgrade using Creees (should be cr333s imho)  and it looks good.

**Comment by sherakama** [comment]
@I was able to run through JSV successfully. Running behat tests now.

**Comment by sherakama** [comment]
behat passed with what I suspect should pass. New tests on old code is jank.

**Comment by jbickar** [comment]
@jbickar likes this 👍

**Pull request merged**
